name: generate breakout svg

on:
  schedule:
  - cron: "0 * * * *"

  workflow_dispatch:         # elle tetikleme

jobs:
  generate-svg:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: generate SVG
        uses: cyprieng/github-breakout@v1
        with:
          github_username: ${{ github.repository_owner }}
          enable_ghost_bricks: false
          bricks_colors: "#1e293b,#334155,#475569,#64748b,#94a3b8"
          paddle_color: "#94a3b8"
          ball_color: "#94a3b8"



      - name: Move generated SVGs to temp
        run: |
          mkdir -p /tmp/breakout-images
          mv output/light.svg /tmp/breakout-images/breakout-light.svg
          mv output/dark.svg  /tmp/breakout-images/breakout-dark.svg
          if [ -f output/custom.svg ]; then cp output/custom.svg /tmp/breakout-images/breakout-custom.svg; fi

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and force-push SVGs to target branch
        run: |
          git checkout --orphan github-breakout
          git rm -rf .
          mkdir images
          mv /tmp/breakout-images/* images/
          git add images
          git commit -m "chore: update GitHub breakout SVGs" || echo "No changes to commit"
          git push --force origin github-breakout
